apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-on-k8s: etcd
  name: etcd0
spec:
  clusterIP: None
  ports:
  - name: client
    port: 2379
    protocol: TCP
  - name: peer
    port: 2380
    protocol: TCP
  selector:
    k8s-on-k8s: etcd
  sessionAffinity: None
